# 7 days
minimumReleaseAge: 10080
# Prevents installation of a package if its trust level has decreased compared to previous releases
trustPolicy: no-downgrade
# pnpm will not install any package that claims to not be compatible with the current Node version
engineStrict: true
