import '@/styles/globals.css'
import { Fira_Code } from 'next/font/google'
import NavBar from '@/components/navbar'
import Footer from '@/components/footer'

const fira_code = Fira_Code({ subsets: ['latin'] })

export const metadata = {
  title: 'Michael Xymitoulias',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={fira_code.className}>
          <header/>
          <NavBar/>
          <main>{children}</main>
          <Footer/>
        </body>
    </html>
  )
}
