import { Fira_Code } from "next/font/google";
import { Email, Github, LinkedIn } from "../components/UI/Icons";
import Navbar from "../components/Navigation/NavBar";
import Footer from "../components/UI/Footer";
import "../styles/globals.css";

export const metadata = {
  title: "Michael Xymitoulias",
  description: "Generated by create next app",
};

const firaCode = Fira_Code({ subsets: ["latin"] });

const menuItems = [
  {
    label: "About",
    url: "/about",
  },
  {
    label: "Articles",
    url: "/articles",
  },
  {
    label: "Projects",
    url: "/projects",
  },
];

const footerItems = [
  {
    label: "e-mail",
    url: "mailto:michxymi@gmail.com",
    icon: <Email />,
  },
  {
    label: "github",
    url: "https://github.com/michxymi",
    icon: <Github />,
  },
  {
    label: "linkedIn",
    url: "https://www.linkedin.com/in/mxymitoulias/",
    icon: <LinkedIn />,
  },
];

const RootLayout = (props) => (
  <html lang="en">
    <body className={firaCode.className}>
      <Navbar menuItems={menuItems} />
      <main>{props.children}</main>
      <Footer menuItems={footerItems} />
    </body>
  </html>
);

export default RootLayout;
