import '../styles/globals.css'
import { Fira_Code } from 'next/font/google'
import NavBar from '../components/navbar'

const fira_code = Fira_Code({ subsets: ['latin'] })

export const metadata = {
  title: 'Michael Xymitoulias',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={fira_code.className}>
          <header></header>
          <nav><NavBar/></nav>
          <main>{children}</main>
          <footer></footer>
        </body>
    </html>
  )
}
